CREATE TABLE `idapi`.`processing_request_status` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CLIENT` INT NULL,
  `LOCKED_ON` TIMESTAMP NULL,
  `PROCESSING_REQUEST_IDENTIFICATION_CODE` INT NULL,
  `UNLOCKED_ON` TIMESTAMP NULL,
  `STATUS` VARCHAR(8) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Client_idx` (`CLIENT` ASC),
  INDEX `fk_Processing_Request_Identification_Code_idx` (`PROCESSING_REQUEST_IDENTIFICATION_CODE` ASC),
  CONSTRAINT `fk_Client`
    FOREIGN KEY (`CLIENT`)
    REFERENCES `idapi`.`client` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Processing_Request_Identification_Code`
    FOREIGN KEY (`PROCESSING_REQUEST_IDENTIFICATION_CODE`)
    REFERENCES `idapi`.`processing_request` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);