SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE TABLE IF NOT EXISTS `configuration_key` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `KEY` VARCHAR(128) NULL,
  PRIMARY KEY (`ID`));

DROP TABLE IF EXISTS `process_config`;

CREATE TABLE IF NOT EXISTS `process_config` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `VALUE` VARCHAR(45) NULL DEFAULT NULL,
  `KEY` INT(11) NOT NULL,
  `CLIENT` INT(11)  NULL  DEFAULT NULL,
  `PROCESS_TYPE` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_process_config_configuration_key1_idx` (`KEY` ASC),
  INDEX `fk_process_config_client1_idx` (`CLIENT` ASC),
  INDEX `fk_process_config_process_type1_idx` (`PROCESS_TYPE` ASC),
  CONSTRAINT `fk_process_config_configuration_key1`
  FOREIGN KEY (`KEY`)
  REFERENCES `configuration_key` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_process_config_client1`
  FOREIGN KEY (`CLIENT`)
  REFERENCES `client` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_process_config_process_type1`
  FOREIGN KEY (`PROCESS_TYPE`)
  REFERENCES `process_type` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
