-- MySQL Workbench Synchronization
-- Generated: 2017-03-01 13:47
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: sasitha madushanka

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `processing_request`
ADD COLUMN `FINAL_RESPONSE` LONGTEXT NULL DEFAULT NULL AFTER `PROCESSING_REQUEST_IDENTIFICATION_CODE`,
ADD COLUMN `PROCESSING_COMPLETED_ON` TIMESTAMP NULL DEFAULT NULL AFTER `FINAL_RESPONSE`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;