package com.fintech.orion.dataabstraction.entities.orion;
// Generated Nov 24, 2017 6:37:53 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AccountMapping generated by hbm2java
 */
@Entity
@Table(name = "account_mapping", catalog = "idapi")
public class AccountMapping implements java.io.Serializable {

    private AccountMappingId id;
    private Client clientByParent;
    private Client clientByChild;

    public AccountMapping() {
    }

    public AccountMapping(AccountMappingId id, Client clientByParent, Client clientByChild) {
        this.id = id;
        this.clientByParent = clientByParent;
        this.clientByChild = clientByChild;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "parent", column = @Column(name = "PARENT", nullable = false)),
            @AttributeOverride(name = "child", column = @Column(name = "CHILD", nullable = false)),
            @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)) })
    public AccountMappingId getId() {
        return this.id;
    }

    public void setId(AccountMappingId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PARENT", nullable = false, insertable = false, updatable = false)
    public Client getClientByParent() {
        return this.clientByParent;
    }

    public void setClientByParent(Client clientByParent) {
        this.clientByParent = clientByParent;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CHILD", nullable = false, insertable = false, updatable = false)
    public Client getClientByChild() {
        return this.clientByChild;
    }

    public void setClientByChild(Client clientByChild) {
        this.clientByChild = clientByChild;
    }

}
