package com.fintech.orion.dataabstraction.entities.orion;
// Generated Nov 24, 2017 6:37:53 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccountMappingId generated by hbm2java
 */
@Embeddable
public class AccountMappingId implements java.io.Serializable {

    private int parent;
    private int child;
    private int id;

    public AccountMappingId() {
    }

    public AccountMappingId(int parent, int child, int id) {
        this.parent = parent;
        this.child = child;
        this.id = id;
    }

    @Column(name = "PARENT", nullable = false)
    public int getParent() {
        return this.parent;
    }

    public void setParent(int parent) {
        this.parent = parent;
    }

    @Column(name = "CHILD", nullable = false)
    public int getChild() {
        return this.child;
    }

    public void setChild(int child) {
        this.child = child;
    }

    @Column(name = "ID", nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof AccountMappingId))
            return false;
        AccountMappingId castOther = (AccountMappingId) other;

        return (this.getParent() == castOther.getParent()) && (this.getChild() == castOther.getChild())
                && (this.getId() == castOther.getId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getParent();
        result = 37 * result + this.getChild();
        result = 37 * result + this.getId();
        return result;
    }

}
