package com.fintech.orion.dataabstraction.entities.orion;
// Generated Feb 18, 2017 5:58:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ConfigurationKey generated by hbm2java
 */
@Entity
@Table(name="configuration_key"
)
public class ConfigurationKey  implements java.io.Serializable {


     private Integer id;
     private String key;
     private Set<ProcessConfig> processConfigs = new HashSet<ProcessConfig>(0);

    public ConfigurationKey() {
    }

    public ConfigurationKey(String key, Set<ProcessConfig> processConfigs) {
       this.key = key;
       this.processConfigs = processConfigs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="KEY", length=128)
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="configurationKey")
    public Set<ProcessConfig> getProcessConfigs() {
        return this.processConfigs;
    }
    
    public void setProcessConfigs(Set<ProcessConfig> processConfigs) {
        this.processConfigs = processConfigs;
    }




}


