package com.fintech.orion.dataabstraction.entities.orion;
// Generated Sep 12, 2016 10:49:51 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * License generated by hbm2java
 */
@Entity
@Table(name="license"
)
public class License  implements java.io.Serializable {


     private int id;
     private Date startDate;
     private Date endDate;
     private Integer requestCount;
     private Set<ProcessTypeLicense> processTypeLicenses = new HashSet<ProcessTypeLicense>(0);
     private Set<ClientLicense> clientLicenses = new HashSet<ClientLicense>(0);

    public License() {
    }

	
    public License(int id) {
        this.id = id;
    }
    public License(int id, Date startDate, Date endDate, Integer requestCount, Set<ProcessTypeLicense> processTypeLicenses, Set<ClientLicense> clientLicenses) {
       this.id = id;
       this.startDate = startDate;
       this.endDate = endDate;
       this.requestCount = requestCount;
       this.processTypeLicenses = processTypeLicenses;
       this.clientLicenses = clientLicenses;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="START_DATE", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="REQUEST_COUNT")
    public Integer getRequestCount() {
        return this.requestCount;
    }
    
    public void setRequestCount(Integer requestCount) {
        this.requestCount = requestCount;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="license")
    public Set<ProcessTypeLicense> getProcessTypeLicenses() {
        return this.processTypeLicenses;
    }
    
    public void setProcessTypeLicenses(Set<ProcessTypeLicense> processTypeLicenses) {
        this.processTypeLicenses = processTypeLicenses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="license")
    public Set<ClientLicense> getClientLicenses() {
        return this.clientLicenses;
    }
    
    public void setClientLicenses(Set<ClientLicense> clientLicenses) {
        this.clientLicenses = clientLicenses;
    }




}


