package com.fintech.orion.dataabstraction.entities.orion;
// Generated Dec 1, 2017 3:03:43 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProcessingRequestStatus generated by hbm2java
 */
@Entity
@Table(name = "processing_request_status", catalog = "idapi")
public class ProcessingRequestStatus implements java.io.Serializable {

    private Integer id;
    private Client client;
    private ProcessingRequest processingRequest;
    private Date lockedOn;
    private Date unlockedOn;
    private String status;

    public ProcessingRequestStatus() {
    }

    public ProcessingRequestStatus(Client client, ProcessingRequest processingRequest, Date lockedOn, Date unlockedOn,
            String status) {
        this.client = client;
        this.processingRequest = processingRequest;
        this.lockedOn = lockedOn;
        this.unlockedOn = unlockedOn;
        this.status = status;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT")
    public Client getClient() {
        return this.client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PROCESSING_REQUEST_IDENTIFICATION_CODE")
    public ProcessingRequest getProcessingRequest() {
        return this.processingRequest;
    }

    public void setProcessingRequest(ProcessingRequest processingRequest) {
        this.processingRequest = processingRequest;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LOCKED_ON", length = 19)
    public Date getLockedOn() {
        return this.lockedOn;
    }

    public void setLockedOn(Date lockedOn) {
        this.lockedOn = lockedOn;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UNLOCKED_ON", length = 19)
    public Date getUnlockedOn() {
        return this.unlockedOn;
    }

    public void setUnlockedOn(Date unlockedOn) {
        this.unlockedOn = unlockedOn;
    }

    @Column(name = "STATUS", length = 8)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
