package com.fintech.orion.dataabstraction.entities.orion;
// Generated Oct 7, 2016 12:44:51 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProcessResource generated by hbm2java
 */
@Entity
@Table(name="process_resource"
    ,catalog="orion"
)
public class ProcessResource  implements java.io.Serializable {


     private Integer id;
     private Process process;
     private Resource resource;
     private String resourceName;

    public ProcessResource() {
    }

    public ProcessResource(Process process, Resource resource, String resourceName) {
       this.process = process;
       this.resource = resource;
       this.resourceName = resourceName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROCESS", nullable=false)
    public Process getProcess() {
        return this.process;
    }
    
    public void setProcess(Process process) {
        this.process = process;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RESOURCE", nullable=false)
    public Resource getResource() {
        return this.resource;
    }
    
    public void setResource(Resource resource) {
        this.resource = resource;
    }

    
    @Column(name="RESOURCE_NAME", nullable=false, length=40)
    public String getResourceName() {
        return this.resourceName;
    }
    
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }




}


