package com.fintech.orion.dataabstraction.entities.orion;
// Generated Sep 12, 2016 10:49:51 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name="resource"
)
public class Resource  implements java.io.Serializable {


     private int id;
     private Client client;
     private ResourceType resourceType;
     private String location;
     private Set<ProcessResource> processResources = new HashSet<ProcessResource>(0);

    public Resource() {
    }

	
    public Resource(int id, Client client, ResourceType resourceType) {
        this.id = id;
        this.client = client;
        this.resourceType = resourceType;
    }
    public Resource(int id, Client client, ResourceType resourceType, String location, Set<ProcessResource> processResources) {
       this.id = id;
       this.client = client;
       this.resourceType = resourceType;
       this.location = location;
       this.processResources = processResources;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT", nullable=false)
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RESOURCE_TYPE", nullable=false)
    public ResourceType getResourceType() {
        return this.resourceType;
    }
    
    public void setResourceType(ResourceType resourceType) {
        this.resourceType = resourceType;
    }

    
    @Column(name="LOCATION", length=128)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="resource")
    public Set<ProcessResource> getProcessResources() {
        return this.processResources;
    }
    
    public void setProcessResources(Set<ProcessResource> processResources) {
        this.processResources = processResources;
    }




}


