package com.fintech.orion.dataabstraction.entities.orion;
// Generated Oct 14, 2016 9:57:19 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name="resource"
    ,catalog="orion"
)
public class Resource  implements java.io.Serializable {


     private Integer id;
     private Client client;
     private Process process;
     private ResourceType resourceType;
     private String location;
     private String resourceIdentificationCode;

    public Resource() {
    }

	
    public Resource(Client client, ResourceType resourceType, String location, String resourceIdentificationCode) {
        this.client = client;
        this.resourceType = resourceType;
        this.location = location;
        this.resourceIdentificationCode = resourceIdentificationCode;
    }
    public Resource(Client client, Process process, ResourceType resourceType, String location, String resourceIdentificationCode) {
       this.client = client;
       this.process = process;
       this.resourceType = resourceType;
       this.location = location;
       this.resourceIdentificationCode = resourceIdentificationCode;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT", nullable=false)
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROCESS")
    public Process getProcess() {
        return this.process;
    }
    
    public void setProcess(Process process) {
        this.process = process;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RESOURCE_TYPE", nullable=false)
    public ResourceType getResourceType() {
        return this.resourceType;
    }
    
    public void setResourceType(ResourceType resourceType) {
        this.resourceType = resourceType;
    }

    
    @Column(name="LOCATION", nullable=false, length=128)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    
    @Column(name="RESOURCE_IDENTIFICATION_CODE", nullable=false, length=40)
    public String getResourceIdentificationCode() {
        return this.resourceIdentificationCode;
    }
    
    public void setResourceIdentificationCode(String resourceIdentificationCode) {
        this.resourceIdentificationCode = resourceIdentificationCode;
    }




}


