package com.fintech.orion.dataabstraction.entities.orion;
// Generated Sep 12, 2016 10:49:51 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ResourceType generated by hbm2java
 */
@Entity
@Table(name="resource_type"
)
public class ResourceType  implements java.io.Serializable {


     private Integer id;
     private String type;
     private Set<Resource> resources = new HashSet<Resource>(0);

    public ResourceType() {
    }

    public ResourceType(String type, Set<Resource> resources) {
       this.type = type;
       this.resources = resources;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="TYPE", length=10)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="resourceType")
    public Set<Resource> getResources() {
        return this.resources;
    }
    
    public void setResources(Set<Resource> resources) {
        this.resources = resources;
    }




}


