package com.fintech.orion.dataabstraction.entities.orion;
// Generated Oct 14, 2016 9:57:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Response generated by hbm2java
 */
@Entity
@Table(name="response"
    ,catalog="orion"
)
public class Response  implements java.io.Serializable {


     private int id;
     private String rawJson;
     private String extractedJson;
     private Set<Process> processes = new HashSet<Process>(0);

    public Response() {
    }

	
    public Response(int id) {
        this.id = id;
    }
    public Response(int id, String rawJson, String extractedJson, Set<Process> processes) {
       this.id = id;
       this.rawJson = rawJson;
       this.extractedJson = extractedJson;
       this.processes = processes;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="RAW_JSON")
    public String getRawJson() {
        return this.rawJson;
    }
    
    public void setRawJson(String rawJson) {
        this.rawJson = rawJson;
    }

    
    @Column(name="EXTRACTED_JSON")
    public String getExtractedJson() {
        return this.extractedJson;
    }
    
    public void setExtractedJson(String extractedJson) {
        this.extractedJson = extractedJson;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="response")
    public Set<Process> getProcesses() {
        return this.processes;
    }
    
    public void setProcesses(Set<Process> processes) {
        this.processes = processes;
    }




}


